export const SET_AIRLINES_OFFSET_LIMIT = 'SET_AIRLINES_OFFSET_LIMIT';
export const FETCH_AIRLINES_START = 'FETCH_AIRLINES_START';
export const FETCH_AIRLINES_SUCCESS = 'FETCH_AIRLINES_SUCCESS';
export const FETCH_AIRLINES_FAIL = 'FETCH_AIRLINES_FAIL';
export const SET_AIRLINES_PAGE = 'SET_AIRLINES_PAGE';

export const SET_AIRCRAFT_OFFSET_LIMIT = 'SET_AIRCRAFT_OFFSET_LIMIT';
export const FETCH_AIRCRAFT_START = 'FETCH_AIRCRAFT_START';
export const FETCH_AIRCRAFT_SUCCESS = 'FETCH_AIRCRAFT_SUCCESS';
export const FETCH_AIRCRAFT_FAIL = 'FETCH_AIRCRAFT_FAIL';
export const SET_AIRCRAFT_PAGE = 'SET_AIRCRAFT_PAGE';
export const UNMOUNT_AIRCRAFT = 'UNMOUNT_AIRCRAFT';

export const SET_AIRPORTS_OFFSET_LIMIT = 'SET_AIRPORTS_OFFSET_LIMIT';
export const FETCH_AIRPORTS_START = 'FETCH_AIRPORTS_START';
export const FETCH_AIRPORTS_SUCCESS = 'FETCH_AIRPORTS_SUCCESS';
export const FETCH_AIRPORTS_FAIL = 'FETCH_AIRPORTS_FAIL';
export const SET_AIRPORTS_PAGE = 'SET_AIRPORTS_PAGE';
export const UNMOUNT_AIRPORTS = 'UNMOUNT_AIRPORTS';

export const SET_FLIGHTS_OFFSET_LIMIT = 'SET_FLIGHTS_OFFSET_LIMIT';
export const FETCH_FLIGHTS_START = 'FETCH_FLIGHTS_START';
export const FETCH_FLIGHTS_SUCCESS = 'FETCH_FLIGHTS_SUCCESS';
export const FETCH_FLIGHTS_FAIL = 'FETCH_FLIGHTS_FAIL';
export const SET_FLIGHTS_PAGE = 'SET_FLIGHTS_PAGE';
export const UNMOUNT_FLIGHTS = 'UNMOUNT_FLIGHTS';

export const SET_AKRX_OFFSET_LIMIT = 'SET_AKRX_OFFSET_LIMIT';
export const FETCH_AKRX_START = 'FETCH_AKRX_START';
export const FETCH_AKRX_SUCCESS = 'FETCH_AKRX_SUCCESS';
export const FETCH_AKRX_FAIL = 'FETCH_AKRX_FAIL';
export const SET_AKRX_PAGE = 'SET_AKRX_PAGE';

export const SET_USERS_OFFSET_LIMIT = 'SET_USERS_OFFSET_LIMIT';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const SET_USERS_PAGE = 'SET_USERS_PAGE';
