export const SET_AIRLINES_OFFSET_LIMIT = 'SET_AIRLINES_OFFSET_LIMIT';
export const FETCH_AIRLINES_START = 'FETCH_AIRLINES_START';
export const FETCH_AIRLINES_SUCCESS = 'FETCH_AIRLINES_SUCCESS';
export const FETCH_AIRLINES_FAIL = 'FETCH_AIRLINES_FAIL';
export const SET_AIRLINES_PAGE = 'SET_AIRLINES_PAGE';